### PR TITLE
Warn the user about Roblox not working with Wine 8.16+

### PR DESCRIPTION
**Pull request by reflexran**

### CODE REVIEW

**Review by Cristiandis — CHANGES_REQUESTED** [review]
Wine 8.16, not 5.16

**Comment by Cristiandis** [comment]
Isnt this fixed by https://github.com/vinegarhq/vinegarhq.github.io/commit/8052f8bd2264b48cd9aff687fc378ef5dd017bff

**Comment by lunarlettuce** [comment]
Please make it more clear that the Flatpak does not need Wine-GE to function.

**Comment by reflexran** [comment]
> Isnt this fixed by [8052f8b](https://github.com/vinegarhq/vinegarhq.github.io/commit/8052f8bd2264b48cd9aff687fc378ef5dd017bff)

Yes, however it is not a bad idea to warn the user before proceeding to the source or package section of the docs, i also included a guide on how to fix this issue inside the troubleshooting section

**Comment by reflexran** [comment]
> Please make it more clear that the Flatpak does not need Wine-GE to function.

I only included the warnings inside the package and source sections, the guide inside the troubleshooting also says that this issue doesn't apply to flatpak

**Comment by apprehensions** [comment]
Handled by requirements section

**Pull request closed without merging**
