### PR TITLE
Add "Reporting issues to WineHQ" page

### PR DESCRIPTION
**Pull request by Noted-Jrelvas**
Part of https://github.com/vinegarhq/vinegar/issues/156

### CODE REVIEW

**Comment by Noted-Jrelvas** [comment]
This looks pretty much complete for me, but I'm open to any feedback and suggestions you might have.

**Comment by Noted-Jrelvas** [comment]
Less verbosity; this guide is only intended for Vinegar developers.

**Review by tacheometry — CHANGES_REQUESTED** [review]

**Comment by Noted-Jrelvas** [comment]
Applied @tacheometry's changes. It made the wording more straightforward. Double negativity is unnecessary.

**Comment by Noted-Jrelvas** [comment]
On hold;

WINEPREFIX can be set in [env]. Directly inside of the config!

~~that's what i suggested all along.~~

**Comment by apprehensions** [comment]
fr ? ong ?! / ?Fr Fr F/r? O NG?G?GG?G?G OGNF ? F?RF ?R?F ?R

**Review by tacheometry — APPROVED** [review]

**Pull request merged**
