### PR TITLE
Make disabling split lock safer, easier and more efficient

### PR DESCRIPTION
**Pull request by reflexran**

### CODE REVIEW

**Comment by apprehensions** [comment]
YIPEEEEEEEEEEEEEe

**Comment by jrelvas-ipc** [comment]
@apprehensions I was reviewing this patch. You merged too early.

**Comment by apprehensions** [comment]
continue with your reveiw

**Comment by apprehensions** [comment]
ime sorry jrela :sob:

**Comment by apprehensions** [comment]
pzol forive me i OWNT REPEAT THIS MISTAKE AGAIN!!!!

**Comment by reflexran** [comment]
literally 1984 😭

**Comment by jrelvas-ipc** [comment]
See 3a1ea63719fdf4d0c452ea88fceeaa8873ea4c2b.

**Comment by jrelvas-ipc** [comment]
See https://github.com/vinegarhq/vinegarhq.github.io/commit/c1b3deb7622af6d73264270cb2afc19ddefe5a9c too.

(Someone hates bullet points)

**Comment by apprehensions** [comment]
pfft wouldnt bem e

**Comment by apprehensions** [comment]
:33333

**Pull request merged**
